services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgis
    restart: unless-stopped
    volumes:
      - ./docker_volumes/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_USER=root
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    restart: unless-stopped
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - ./docker_volumes/grafana-data:/var/lib/grafana

  rldownload:
    image: uwm/umwelt_realtime_downloader:latest
    container_name: rldownload
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:somepassword@db:5432/postgres
      - PYTHONUNBUFFERED=1

  rlpredictions:
    image: uwm/umwelt_realtime_predictions:latest
    container_name: rlpredictions
    build:
      context: .
      dockerfile: Dockerfile_Prediction
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:somepassword@db:5432/postgres
      - PYTHONUNBUFFERED=1
    volumes:
      - ./docker_volumes/models:/app/models
